import sqlalchemy as sa

from alembic import op

#from lib.util_datetime import tzware_datetime
#from lib.util_sqlalchemy import AwareDateTime


"""
addresses arent unique

Revision ID: 71f439652703
Revises: f75285022b33
Create Date: 2016-09-19 10:18:54.263482
"""

# Revision identifiers, used by Alembic.
revision = '71f439652703'
down_revision = 'f75285022b33'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'organizations_address_key', 'organizations', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'organizations_address_key', 'organizations', ['address'])
    ### end Alembic commands ###
