import sqlalchemy as sa

from alembic import op

#from lib.util_datetime import tzware_datetime
#from lib.util_sqlalchemy import AwareDateTime


"""
panel colors

Revision ID: cae7b15bbc02
Revises: e4e7c1e16603
Create Date: 2016-09-22 11:26:45.542054
"""

# Revision identifiers, used by Alembic.
revision = 'cae7b15bbc02'
down_revision = 'e4e7c1e16603'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('terms', sa.Column('color', sa.String(length=6), nullable=True))
    op.alter_column('terms', 'term',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.drop_constraint(u'terms_term_key', 'terms', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'terms_term_key', 'terms', ['term'])
    op.alter_column('terms', 'term',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.drop_column('terms', 'color')
    ### end Alembic commands ###
