import sqlalchemy as sa

from alembic import op

#from lib.util_datetime import tzware_datetime
#from lib.util_sqlalchemy import AwareDateTime


"""
google map zoom

Revision ID: e4e7c1e16603
Revises: 71f439652703
Create Date: 2016-09-19 11:36:19.450889
"""

# Revision identifiers, used by Alembic.
revision = 'e4e7c1e16603'
down_revision = '71f439652703'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('address_zoom', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'terms_term_key', 'terms', ['term'])
    ### end Alembic commands ###
