import sqlalchemy as sa

from alembic import op

#from lib.util_datetime import tzware_datetime
#from lib.util_sqlalchemy import AwareDateTime


"""
rgba colors are longer than six chars

Revision ID: 2b5f681072a6
Revises: cae7b15bbc02
Create Date: 2016-09-22 12:28:53.435788
"""

# Revision identifiers, used by Alembic.
revision = '2b5f681072a6'
down_revision = 'cae7b15bbc02'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
